# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gates_bdf/gates_bdf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_bdf || ORIG_REF_NAME==gates_bdf} -quiet] -quiet

# IP: bd/gates_bdf/ip/gates_bdf_util_vector_logic_0_0/gates_bdf_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_bdf_util_vector_logic_0_0 || ORIG_REF_NAME==gates_bdf_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/gates_bdf/gates_bdf_ooc.xdc
